work_dir: ./UCI_workdir/UCI_ChebGCN_Dili

debug: False
# feeder
data_path:  /hy-tmp/UCI_HAR/{}.npy





# model
model: model.NEWMVUAGCN.ChebGCN1


# model_args:
#   hidden_feats: [6,24,48,18]
#   hidden_feats2: [3,6,24,18]
#   out_feats: 6
# feats_split: [6,3]

# gcn
model_args:
  hidden_feats: [9,27,54,18]
  out_feats: 6

flag: 1
Dili: 1
DS: 0


# weights: ./OPPORTUNITYworkdir/OPPORTUNITY_ChebGCN_Multi_DS/best_acc_weights.pt
# optim
weight_decay: 0.00005
base_lr: 0.001
step: [30, 40]
optimizer : Adam
lr_decay_rate: 0.0001
# training
num_epoch: 80

batch_size: 64
test_batch_size: 64

nesterov: True



