
work_dir: ./MHEALTH_workdir/MHEALTH_ChebGCN_Dili

debug: False
# feeder
data_path:  /hy-tmp/MHEALTH/{}.npy


# model
model: model.NEWMVUAGCN.ChebGCN1

#
# model_args:
#   hidden_feats: [9,27,54,27]
#   hidden_feats2: [6,18,36,18]
#   hidden_feats3: [6,18,36,18]
#   out_feats: 12
# feats_split: [9,15]



flag: 1
Dili: 1
DS: 0

# gcn
model_args:
  hidden_feats: [21,42,84,42]
  out_feats: 12



weights: ./MHEALTH_workdir/MHEALTH_ChebGCN/best_acc_weights.pt
# optim
weight_decay: 0.00005
base_lr: 0.001
step: [30, 40]
optimizer : Adam
lr_decay_rate: 0.0001
# training
num_epoch: 60

batch_size: 64
test_batch_size: 64

nesterov: True



